[package]
name = "shelflife"
version = "0.1.0"
authors = ["wilnil"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.19"
serde = "1.0.97"
chrono = { version = "0.4.7", features = ["serde"] }
dotenv = "0.14.1"
mongodb = "0.3.12"
prettytable-rs = "0.8.0"

[lib]
name = "shelflife"
path = "src/lib.rs"

[[bin]]
name = "shelflife"
path = "src/bin/main.rs"
